---
### todo move to firewall role
- name: add http port
  when: "'web' in group_names"
  ansible.builtin.firewalld:
    zone: public
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: restart service firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted