---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Set password for the default PostgreSQL user
  ansible.builtin.command: sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ postgres_password }}';"
