---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Create PostgreSQL user
  become: true
  become_user: postgres
  community.general.postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"

- name: Create PostgreSQL database
  become: true
  become_user: postgres
  community.general.postgresql_db:
    name: "{{ postgres_db }}"
    owner: "{{ postgres_user }}"
