---
- name: Download MySQL APT configuration package
  get_url:
    url: https://repo.mysql.com/mysql-apt-config_0.8.32-1_all.deb
    dest: /tmp/mysql-apt-config_0.8.32-1_all.deb

- name: Install MySQL APT configuration package
  apt:
    deb: /tmp/mysql-apt-config_0.8.32-1_all.deb

- name: Installing mysql server on {{ ansible_distribution }} {{ ansible_distribution_release }}
  apt:
    name: [mysql-server, python3-pymysql, python3-cryptography, python3-pexpect]
    update_cache: yes
    state: latest

#- name: copy my.cnf
#  template:
#    src: my.cnf
#    dest: /etc/mysql/mysql.conf.d/mysqld.cnf

- name: Restart MySQL Server
  systemd:
    name: mysql.service
    state: restarted
    enabled: yes

- name: Create a new db user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    name: root
    host: "%"
    plugin_auth_string: "{{ db_root_password }}"
    plugin: caching_sha2_password
    state: present
    priv: '*.*:ALL,GRANT'
