---
- name: Installing dependencies for Debian
  ansible.builtin.apt:
    name: [gnupg]
    update_cache: yes
    state: present

- name: Download MySQL APT configuration package
  ansible.builtin.get_url:
    url: https://repo.mysql.com/mysql-apt-config_0.8.34-1_all.deb
    dest: /tmp/mysql-apt-config_0.8.34-1_all.deb

- name: Install MySQL APT configuration package
  ansible.builtin.apt:
    deb: /tmp/mysql-apt-config_0.8.34-1_all.deb

- name: Installing mysql server on {{ ansible_distribution }} {{ ansible_distribution_release }}
  ansible.builtin.apt:
    name: [mysql-server, python3-pymysql]
    update_cache: yes
    state: latest

- name: Restart MySQL Server
  ansible.builtin.systemd:
    name: mysql.service
    state: restarted
    enabled: yes

- name: Create a new db user
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    name: root
    host: "%"
    plugin_auth_string: "{{ db_root_password }}"
    plugin: caching_sha2_password
    state: present
    priv: '*.*:ALL,GRANT'
