---
# https://repo.mysql.com/mysql84-community-release-fc42-1.noarch.rpm
# https://repo.mysql.com/mysql84-community-release-el9-1.noarch.rpm

- name: Installing dependencies
  ansible.builtin.dnf:
    name: gnupg
    update_cache: yes
    state: present

- name: Import MySQL GPG key
  ansible.builtin.rpm_key:
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
    state: present

- name: Add mysql repository
  ansible.builtin.dnf:
    name: https://repo.mysql.com/mysql84-community-release-el9-1.noarch.rpm
    state: present

- name: Installing mysql
  ansible.builtin.dnf:
    name: [python3-PyMySQL, python3-cryptography, mysql-community-server]
    update_cache: yes
    state: latest

- name: stop mysql server
  ansible.builtin.systemd:
    name: mysqld.service
    state: stopped
    enabled: yes

- name: the following command which will allow the database to start without loading the grant tables or networking.
  command: systemctl set-environment MYSQLD_OPTS="--skip-grant-tables --skip-networking"

- name: start mysql Server
  systemd:
    name: mysqld.service
    state: started
    enabled: yes

- name: Set root password
  command: mysql -u root -e "FLUSH PRIVILEGES; ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ db_root_password }}'; FLUSH PRIVILEGES;"

- name: Create root@%
  command: mysql -u root -p{{ db_root_password }} -e "FLUSH PRIVILEGES; CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '{{ db_root_password }}'; GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"

- name: Revert the environment settings to allow the database to start with grant tables and networking
  command: systemctl unset-environment MYSQLD_OPTS

- name: Restart MySQL Server
  systemd:
    name: mysqld.service
    state: restarted
    enabled: yes

- name: Create a new db user
  mysql_user:
    login_user: root
    login_password: "{{ db_root_password }}"
    name: ismail
    host: "%"
    plugin_auth_string: "{{ db_root_password }}"
    plugin: caching_sha2_password
    state: present
    priv: '*.*:ALL,GRANT'